browser: "chrome"                # "chrome" or "firefox"

# Chrome settings
chrome_user_data_dir: "/home/lance/.config/chromium"
chrome_profile_dir: "Default"
chrome_binary_path: "/usr/bin/chromium"            # optional, e.g. "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
chromedriver_path: "/usr/bin/chromedriver"             # optional, e.g. "/usr/local/bin/chromedriver"
chrome_extension_id: "lmjnegcaeklhafolokijcfjliaokphfk"  # Video DownloadHelper Chrome extension ID

# Firefox settings
firefox_profile_path: "/Users/lance/Library/Application Support/Firefox/Profiles/qf5j5k02.default-release"
firefox_binary_path: "/usr/bin/firefox"
geckodriver_path: "/usr/local/bin/geckodriver"
firefox_extension_id: "66de4938-4732-4da4-ad95-15aa10bfa7c4"  # Video DownloadHelper Firefox extension ID

course_url: "https://learn.deeplearning.ai/courses/claude-code-a-highly-agentic-coding-assistant/lesson/66b35/introduction"
extension_popup_path: "content/sidebar.html"
download_file_prefix: "VDH"         # downloaded file will be {prefix}_{video_name}.mp4
download_watch_dir: "~/Downloads"
output_dir: "./downloads"
download_timeout: 800
page_load_wait: 3
